### PR TITLE
convert intermediate file EOLs to pure \n format

### PR DESCRIPTION
**Pull request by facchinm**
otherwise all processing on ino file will likely fail
solves #114 
@matteosuppo @cmaglie @matthijskooijman

### CODE REVIEW

**Comment by matteosuppo** [comment]
Looks fine to me

**Comment by 00alis** [comment]
@cmaglie would you have a look at it too? thanks!

**Comment by cmaglie** [comment]
LGTM :+1:

I'd just add a comment in `src/arduino.cc/builder/test/eol_processing/sketch.ino` to explain that the file contains DOS-style line endings.

**Comment by 00alis** [comment]
Great! Could someone merge and launch a build? So this agìfternoon we can test it on Create and release it tomorrow.

Thanks!

**Pull request merged**
