### PR TITLE
Limit recursive sketch compilation to the `src` directory

### PR DESCRIPTION
**Pull request by matthijskooijman**

### CODE REVIEW

**Comment by bperrybap** [comment]
So is this going to fixed or not?
It almost sounds like it isn't be perceived as an issue.

@matthijskooijman 
This more than just about recursive compilation.
It affects use of include files as well.
If the build system is not going to build in place (in the original sketch directory) then it must ensure that all sub directories under the main sketch directory are also copied into the tmp build area.

There is no need for the build system to have this restriction to try enforce a set of artificial limitations, especially when it is enforcing limitations that have not existed in the past.
This will break many existing projects.

This is very similar to the restrictions that were placed on new 1.5x libraries in the  IDE releases 1.5 through  1.5.5 where a library was totally ignored if the code wasn't down under a directory named "src".
Thank goodness the Arduino team realized the error of that decision.

This choice to not allow sub directories in a sketch folder seems like a similar decision.
- an artificial restriction that breaks backward compatibility

**Comment by bperrybap** [comment]
I posted a suggested very simple fix in the other issue here:
https://github.com/arduino/Arduino/issues/5186
That I think could solve most of the issues people are encountering.

**Comment by Chris--A** [comment]
> So is this going to fixed or not?
It almost sounds like it isn't being perceived as an issue.

I agree this is a very large change in behavior for a minor revision.

To follow semantic versioning, shouldn't this have bumped the IDE to 2.0.0, not 1.6.10 -- like what happened when the API changed from 0023 - 1.0.0. The purpose for this type of versioning is to let people know there may be things missing or at the least, breaking changes which they should expect.

A bump from 1.6.9 to 1.6.10 should only tell me there are either improvements, new features, and bug fixes.

**Comment by PaulStoffregen** [comment]
This may be stating the overly obvious, but the Arduino IDE as a complete system doesn't really support sources in sketch subdirs as long as the IDE's editor doesn't support at least showing the files to users.

I have personally helped at least a couple end users who ended up with an extremely confusing (and very tough to diagnose remotely) situation where somehow a subdir got created with more files having conflicting copies of their variables.  When the extra files are all but invisible to an end user, it's a recipe for terrible confusion.

On these github issues, it's easy to focus on technical details.  Just want to post a gentle reminder that whatever is done in the builder needs to be carefully considered in how it's presented to use users by the GUI.

**Comment by Alexia** [comment]
I am another victim of this change.  I have lost eight hours messing with my code bases trying to figure out why nothing would compile("undefined reference to") on one computer and why it would not find any files at all on another computer.(I upgraded from Arduino IDE 1.6.5 to 1.8.2.)

This really should have been a major revision changed to 2.x.x as @Chris--A mentioned or at least have system built in place to warn users when they #include from non-whitelisted directories.  As it stands now the Arduino documentation does not mention any limitations to include folder structure and the error messages thrown are cryptic when the file paths appear to be typed correctly.

**Comment by mlewand** [comment]
I also spent a good time googling around today. It's very awkward from programmer perspective, any other compiler never had a limitation like that.

**Comment by Pharap** [comment]
Is this ever going to be fixed?

This is a ridiculously arbitrary limitation.

**Comment by Ryushane** [comment]
It's really sucks. Wasted a whole night because of this feature.

**Comment by Alexia** [comment]
I doubt they will ever go back and fix the versioning to reflect this major change.  So I doubt anything else will happen due to the lack of developer comment follow up.

**Comment by bperrybap** [comment]
> I doubt they will ever go back and fix the versioning to reflect this major change. So I doubt anything else will happen due to the lack of developer comment follow up.

It is ironic that the library manager back-end scripts require that Arduino libraries use semver compliant version numbers/strings and in their github git tags, yet the IDE totally ignores the point of semver versioning.

IMO, the issue with the src directory and sub directory build issues is that the IDE made some wrong-headed decisions quite a while back. One of those was to not compile with the sources left in place.
There is no need to ever copy the sources to a different location for compiling/linking even if a temporary "build" area is used to hold the objects as the objects don't have to live in the same place as the sources. The IDE should also recurse and locate every .h .c .cpp .pde and .ino under the top level sketch/library directory. 
I still don't understand why these types of artificial restrictions are often thrown into the IDE.
In many cases they are simply not helpful and there have been several cases through the years where they are eventually removed.

**Comment by per1234** [comment]
The restriction of recursive compilation to the `src` subfolder was done in response to multiple bug reports from people who had separate programs stored in subfolders of their sketch. Prior to the introduction of arduino-builder in Arduino IDE 1.6.6, no recursive compilation was done and so that caused no problems for these sketches. After indiscriminate recursive compilation was introduced they would no longer compile.

Indiscriminate recursive compilation was done from Arduino IDE 1.6.6 to 1.6.9 but this feature was never advertised so I doubt many people discovered and took advantage of the new feature over that time and then found their code to be broken by the restriction of recursive compilation to the `src` subfolder introduced in Arduino IDE 1.6.10. That said, I'm very much in favor of faithfully following semver.

I think restricting recursive compilation to the `src` folder is reasonable and can't see why anyone would consider this to be such an issue. 

The feature does really need to be documented so that more people will be aware of this very useful feature. I would like to see an Arduino Sketch Specification page created, similar to the existing [Arduino Library Specification](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification) page.

**Comment by bperrybap** [comment]
>  I'm very much in favor of faithfully following semver.

@per1234 , maybe you (and all of us) could start to put some pressure on the Arduino dev team to actually follow it with their s/w releases, especially for things  like the IDE package?

I think part of the issue is that for years everything is called "Arduino" , From the board, to the "language" to the "tool" use to build the sketches. It can make it difficult when trying to refer to various sub components - which might also have their own versioning.

I download and used Arduino to upload a sketch written in Arduino, to my Arduino....

And then there are several sub-components within the Arduino IDE.

But at least IMO,  I agree with @Alexia  that since the IDE that is download has its own version number, that the version number for the Arduino build package/IDE should be a semver version number and follow semver versioning.
Which means that the when changes that affect how sketches are built are made, that isn't just a minor number bump.

As it is now, the IDE version number does not seem to follow semver semantics at all.

--- bill

**Comment by Pharap** [comment]
> but this feature was never advertised so I doubt many people discovered and took advantage of the new feature over that time and then found their code to be broken by the restriction of recursive compilation to the src subfolder introduced in Arduino IDE 1.6.10

I am one of the people for whom this change (restriction to `src`) broke code.
I know of one or two other people for whom this change broke code.
It wasn't until much later that I found out what had actually happened.

 > I think restricting recursive compilation to the src folder is reasonable and can't see why anyone would consider this to be such an issue.

I take issue with it because I believe it to be a surprising restriction contrary to common practice and expectations.
I believe that indiscriminate recursive compilation is in fact the behaviour most people would expect.

Furthermore I take issue with it because it forces people to have one of their folders follow a particular arbitrary naming convention (i.e. the use of contractions) that may otherwise look out of place in the rest of their code.

---

I would also be interested to know why people were attempting to have more than one program per 'sketch'.
To me that seems like a somewhat unusual expectation.

**Pull request merged**
