### PR TITLE
Allow precompiled libs

### PR DESCRIPTION
**Pull request by facchinm**
Allow dynamic and static libraries linking at runtime.
Please note that no library of this kind will be included in the library manager since we would be unable to enforce that the license is compliant with the actual library "content"

### CODE REVIEW

**Comment by kgoveas** [comment]
@facchinm ,

Do you know when this will be part of the Arduino-builder release?

**Comment by Corjan85** [comment]
Hi,

Is there any news on when this will be included into the official Arduino release?
The wiki says it should have been available in 1.8.6, but it didn't make it it seems :)

Corjan

**Comment by facchinm** [comment]
@Corjan85 it is included in IDE 1.8.6 and upwards; for an example of the usage, take a look at  https://github.com/arduino/ArduinoCore-samd/commit/37c8d4f36a86824def2e16a6e3701a4b41ea0078 (the commit is used to link https://github.com/vidor-libraries/USBBlaster library)

**Comment by facchinm** [comment]
The rule name has been changed [here](https://github.com/arduino/arduino-builder/commit/ffe96696f3447613e7975e7ba99f63db4349ed4c) to avoid clash with already defined flags

**Comment by Corjan85** [comment]
Hi,


Thanks for your reply.

I think have done the same as the USBBlaster library. This is my library.properties:
```
name=SI Message Port
version=1.0.0
author=Sim Innovations
maintainer=Sim Innovations <corjan@siminnovations.com>
sentence=Allows to couple Arduino projects to Air Manager or Air Player
paragraph=
category=Device Control
url=https://www.siminnovations.com
architectures=*
precompiled=true
ldflags=-lMessagePort -lMessagePortDriver -lSiBase
```


This is what happens during the linking step:

`C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-gcc" -w -Os -g -flto -fuse-linker-plugin -Wl,--gc-sections -mmcu=atmega328p -o "C:\\Users\\corja\\AppData\\Local\\Temp\\arduino_build_186642/BasicExample.ino.elf" "C:\\Users\\corja\\AppData\\Local\\Temp\\arduino_build_186642\\sketch\\BasicExample.ino.cpp.o" "C:\\Users\\corja\\AppData\\Local\\Temp\\arduino_build_186642\\libraries\\SiMessagePort\\si_message_port.cpp.o" "C:\\Users\\corja\\AppData\\Local\\Temp\\arduino_build_186642/core\\core.a" "-LC:\\Users\\corja\\AppData\\Local\\Temp\\arduino_build_186642" -lm
`

It seems the ldflags are ignored. The custom build arduino_builder.exe higher up in this post seems to add the ldflags.

Could it maybe be a feature that is only supported on SAM devices? Since the USBBlaster only targets SAM. I'm targetting atmega328p, atmega2560 and ATmega32U4.


Any help is appreciated,

Corjan

**Comment by Corjan85** [comment]
Forget to tell, but I'm using Arduino 1.8.7.

I have done a reinstall, and made sure to delete everything from program files and user documents folder, just in case...

Corjan

**Comment by facchinm** [comment]
Yes, at the moment only `samd` core is supported (in beta). Adding the flag to avr core is trivial but we haven't done it yet; anyway, if you want to experiment on your library and then propose a PR to https://github.com/arduino/ArduinoCore-avr I'll be glad to take a look and merge it!

**Comment by Corjan85** [comment]
Ah, that makes sense :)
Will make a fork and see how far I get.

**Pull request merged**
