### PR TITLE
Parallel compiling: arduino-builder will leverage your multi core pc

### PR DESCRIPTION
**Pull request by copercini**
If -jobs X param is specified and X is greater than 0, arduino-builder won't spawn more than X processes. Fixes https://github.com/arduino/arduino-builder/issues/17

- Rebased from Federico Fissore branch https://github.com/arduino/arduino-builder/commit/0a3d888439ee369d7f4cc2333619e66fc7dcf672
- Add HumanTagsLogger compatibility
- Remove an if which suppress some GCC error messages here: https://github.com/arduino/arduino-builder/commit/0a3d888439ee369d7f4cc2333619e66fc7dcf672#diff-8f074e2b3fc911dbe8255891fc1a9b13R96

### CODE REVIEW

**Comment by copercini** [comment]
Compilation time benchmarks (Based on Travis CI builds )

benchmark compilation time

**Comment by facchinm** [comment]
@ArduinoBot build this please

**Comment by matthijskooijman** [comment]
@copercini, I couldn't manage to reproduce the slowness of the PR236 build (see https://github.com/arduino/arduino-builder/pull/236#issuecomment-348198246). Any chance that was just a measurement error on your side (system under load perhaps)? Could you see if you can reproduce this slowness again?

**Comment by copercini** [comment]
@matthijskooijman The data used in the table comes from this build: https://travis-ci.org/arduino/arduino-builder/builds/243798460
In the new builds of https://github.com/arduino/arduino-builder/pull/236 like https://travis-ci.org/arduino/arduino-builder/builds/309526510 the compilation time is similar to others PRs, so everything looks normal

So yes, probably the slowness comes from something in Travis CI just at this time and your PR is fine

**Comment by matthijskooijman** [comment]
Thanks for checking!

**Comment by kubark42** [comment]
This seems useful. Especially on Windows, where Arduino seems to build more slowly on a 2018 Surface Book 2 than a 2014 Macbook Pro. @copercini was there a blocker?

**Comment by cmaglie** [comment]
This one has been manually merged.

**Comment by PaulStoffregen** [comment]
Any chance for a 1.8.6 release with this feature?

I've been using 1.8.5 with 1.9's builder and preprocessor, and the new preprocessor rule added to 1.8.5's platform.txt.  It's really awesome for larger projects with a lot of code!

I'm sure much of the Arduino community would love a near-term stable 1.8.6 release with this feature....

**Pull request closed without merging**
