### PR TITLE
add #line directive to additional source files #1

### PR DESCRIPTION
**Pull request by slady**
improvement for https://github.com/arduino/arduino-builder/issues/323

### CODE REVIEW

**Comment by slady** [comment]
I realized I made a mistake and forgot the important "QuoteCppString"

**Comment by matthijskooijman** [comment]
FYI, you could have (force-)pushed to the existing branch to update this PR rather than create a new one (but no harm done of course, just for future reference).

**Comment by slady** [comment]
Oh sorry, did not know that was possible. Even though experienced with git,
I am new to GitHub. Thank you for telling me!
BTW, how long could it take for this change to get to the main branch and
main build?

čt 20. 6. 2019 v 13:08 odesílatel Matthijs Kooijman <
notifications@github.com> napsal:

**Comment by FrankBoesing** [comment]
Arduino: Most changes need months(best case) to years - 99% of suggestions are accepted never.
For the builder it seems to by slightly better..

**Comment by slady** [comment]
Thanks for your honest answer, though it was not very encouraging...

**Comment by FrankBoesing** [comment]
Yes, I'm not sure why they use Github. It's so miselading for other as they think they can contribute.

**Comment by matthijskooijman** [comment]
In practice, there's a lot more contributions than there is manpower to review, polish and eventually merge them, unfortunately. This seems like a fairly small change, so that makes things easier. I'm not the one that decides whether to merge something, but I can perhaps help things along by providing a review :-)

**Comment by slady** [comment]
Thank you for trying to help!

**Comment by slady** [comment]
I double checked the contents of the additional files list, it can contain files with these extensions:
.h .c .hpp .hh .cpp .s
Hope all of them can start with the #line directive.

**Comment by matthijskooijman** [comment]
Please reply in the other PR, since here it won't be seen :-)

**Comment by slady** [comment]
Moved it there. Added a little more.
Hope somebody reads it in this century.

**Pull request closed without merging**
